//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.General", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activ.
        /// </summary>
        internal static string Activ {
            get {
                return ResourceManager.GetString("Activ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator de performanta.
        /// </summary>
        internal static string Activitate {
            get {
                return ResourceManager.GetString("Activitate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am uitat parola / Forgot password.
        /// </summary>
        internal static string Amuitatparola {
            get {
                return ResourceManager.GetString("Amuitatparola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anul.
        /// </summary>
        internal static string An {
            get {
                return ResourceManager.GetString("An", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizator.
        /// </summary>
        internal static string Angajat {
            get {
                return ResourceManager.GetString("Angajat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobare.
        /// </summary>
        internal static string Aprobare {
            get {
                return ResourceManager.GetString("Aprobare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobate.
        /// </summary>
        internal static string Aprobate {
            get {
                return ResourceManager.GetString("Aprobate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badges &amp; Stiri.
        /// </summary>
        internal static string BadgesStiri {
            get {
                return ResourceManager.GetString("BadgesStiri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banca.
        /// </summary>
        internal static string Banca {
            get {
                return ResourceManager.GetString("Banca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aproba.
        /// </summary>
        internal static string btnAproba {
            get {
                return ResourceManager.GetString("btnAproba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inapoi.
        /// </summary>
        internal static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renunta.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicare.
        /// </summary>
        internal static string btnClone {
            get {
                return ResourceManager.GetString("btnClone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sterge.
        /// </summary>
        internal static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica.
        /// </summary>
        internal static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iesire.
        /// </summary>
        internal static string btnExit {
            get {
                return ResourceManager.GetString("btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Init.
        /// </summary>
        internal static string btnInit {
            get {
                return ResourceManager.GetString("btnInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nou.
        /// </summary>
        internal static string btnNew {
            get {
                return ResourceManager.GetString("btnNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontaj pe Angajat.
        /// </summary>
        internal static string btnPeAng {
            get {
                return ResourceManager.GetString("btnPeAng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontaj pe Zi.
        /// </summary>
        internal static string btnPeZi {
            get {
                return ResourceManager.GetString("btnPeZi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string btnPrint {
            get {
                return ResourceManager.GetString("btnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontajul Echipei.
        /// </summary>
        internal static string btnPtjEchipa {
            get {
                return ResourceManager.GetString("btnPtjEchipa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalcul.
        /// </summary>
        internal static string btnRecalc {
            get {
                return ResourceManager.GetString("btnRecalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respinge.
        /// </summary>
        internal static string btnRespinge {
            get {
                return ResourceManager.GetString("btnRespinge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respins.
        /// </summary>
        internal static string btnRespins {
            get {
                return ResourceManager.GetString("btnRespins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salveaza.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arata.
        /// </summary>
        internal static string btnShow {
            get {
                return ResourceManager.GetString("btnShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfera.
        /// </summary>
        internal static string btnTransfera {
            get {
                return ResourceManager.GetString("btnTransfera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizeaza.
        /// </summary>
        internal static string btnUpdate {
            get {
                return ResourceManager.GetString("btnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calificativ.
        /// </summary>
        internal static string Calificativ {
            get {
                return ResourceManager.GetString("Calificativ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite anulare.
        /// </summary>
        internal static string Campbifa {
            get {
                return ResourceManager.GetString("Campbifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cereri.
        /// </summary>
        internal static string Cereri {
            get {
                return ResourceManager.GetString("Cereri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip aditional solicitare.
        /// </summary>
        internal static string Compensare {
            get {
                return ResourceManager.GetString("Compensare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip aditional solicitare 2.
        /// </summary>
        internal static string CompensareBanca {
            get {
                return ResourceManager.GetString("CompensareBanca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip aditional solicitare 1.
        /// </summary>
        internal static string CompensarePlata {
            get {
                return ResourceManager.GetString("CompensarePlata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competenta.
        /// </summary>
        internal static string Competenta {
            get {
                return ResourceManager.GetString("Competenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma parola.
        /// </summary>
        internal static string ConfirmaParola {
            get {
                return ResourceManager.GetString("ConfirmaParola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contul meu.
        /// </summary>
        internal static string ContulMeu {
            get {
                return ResourceManager.GetString("ContulMeu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuvenite.
        /// </summary>
        internal static string Cuvenite {
            get {
                return ResourceManager.GetString("Cuvenite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuvenite An.
        /// </summary>
        internal static string CuveniteAn {
            get {
                return ResourceManager.GetString("CuveniteAn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Inceput.
        /// </summary>
        internal static string DataInceput {
            get {
                return ResourceManager.GetString("DataInceput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Sfarsit.
        /// </summary>
        internal static string DataSfarsit {
            get {
                return ResourceManager.GetString("DataSfarsit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date din view.
        /// </summary>
        internal static string datedinview {
            get {
                return ResourceManager.GetString("datedinview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denumire.
        /// </summary>
        internal static string Denumire {
            get {
                return ResourceManager.GetString("Denumire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentarii status.
        /// </summary>
        internal static string Descriere {
            get {
                return ResourceManager.GetString("Descriere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicare.
        /// </summary>
        internal static string Duplicare {
            get {
                return ResourceManager.GetString("Duplicare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluare proprie.
        /// </summary>
        internal static string Evaluareangajat {
            get {
                return ResourceManager.GetString("Evaluareangajat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obiective.
        /// </summary>
        internal static string Evaluari {
            get {
                return ResourceManager.GetString("Evaluari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExplicatiiCalificativ.
        /// </summary>
        internal static string ExplicatiiCalificativ {
            get {
                return ResourceManager.GetString("ExplicatiiCalificativ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        internal static string F10003 {
            get {
                return ResourceManager.GetString("F10003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr. tabela.
        /// </summary>
        internal static string F70101 {
            get {
                return ResourceManager.GetString("F70101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string F70102 {
            get {
                return ResourceManager.GetString("F70102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola.
        /// </summary>
        internal static string F70103 {
            get {
                return ResourceManager.GetString("F70103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denumire.
        /// </summary>
        internal static string F70104 {
            get {
                return ResourceManager.GetString("F70104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string F70105 {
            get {
                return ResourceManager.GetString("F70105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola expira.
        /// </summary>
        internal static string F70111 {
            get {
                return ResourceManager.GetString("F70111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola complexa.
        /// </summary>
        internal static string F70112 {
            get {
                return ResourceManager.GetString("F70112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schimba Parola.
        /// </summary>
        internal static string F70113 {
            get {
                return ResourceManager.GetString("F70113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocat.
        /// </summary>
        internal static string F70114 {
            get {
                return ResourceManager.GetString("F70114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In...zile.
        /// </summary>
        internal static string F70121 {
            get {
                return ResourceManager.GetString("F70121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data modificare.
        /// </summary>
        internal static string F70122 {
            get {
                return ResourceManager.GetString("F70122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cale salvari.
        /// </summary>
        internal static string F70123 {
            get {
                return ResourceManager.GetString("F70123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluturas Salariu.
        /// </summary>
        internal static string fluturassalariu {
            get {
                return ResourceManager.GetString("fluturassalariu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limba.
        /// </summary>
        internal static string IdLimba {
            get {
                return ResourceManager.GetString("IdLimba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activ.
        /// </summary>
        internal static string lblActiv {
            get {
                return ResourceManager.GetString("lblActiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denumire.
        /// </summary>
        internal static string lblDenumire {
            get {
                return ResourceManager.GetString("lblDenumire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string lblId {
            get {
                return ResourceManager.GetString("lblId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limba.
        /// </summary>
        internal static string Limba {
            get {
                return ResourceManager.GetString("Limba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limbi.
        /// </summary>
        internal static string Limbi {
            get {
                return ResourceManager.GetString("Limbi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luna de lucru.
        /// </summary>
        internal static string LunaDeLucru {
            get {
                return ResourceManager.GetString("LunaDeLucru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managerul N+1.
        /// </summary>
        internal static string ManagerulN1 {
            get {
                return ResourceManager.GetString("ManagerulN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managerul N+2.
        /// </summary>
        internal static string ManagerulN2 {
            get {
                return ResourceManager.GetString("ManagerulN2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meniuri.
        /// </summary>
        internal static string meniuri {
            get {
                return ResourceManager.GetString("meniuri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica.
        /// </summary>
        internal static string Modifica {
            get {
                return ResourceManager.GetString("Modifica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obiectiv - Descriere.
        /// </summary>
        internal static string Obiectiv {
            get {
                return ResourceManager.GetString("Obiectiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola.
        /// </summary>
        internal static string Parola {
            get {
                return ResourceManager.GetString("Parola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola.
        /// </summary>
        internal static string Parola2 {
            get {
                return ResourceManager.GetString("Parola2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Info Chiosc.
        /// </summary>
        internal static string PINInfoChiosc {
            get {
                return ResourceManager.GetString("PINInfoChiosc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planificate.
        /// </summary>
        internal static string Planificate {
            get {
                return ResourceManager.GetString("Planificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plata.
        /// </summary>
        internal static string Plata {
            get {
                return ResourceManager.GetString("Plata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Pondere {
            get {
                return ResourceManager.GetString("Pondere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontaje.
        /// </summary>
        internal static string Pontaje {
            get {
                return ResourceManager.GetString("Pontaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozitie.
        /// </summary>
        internal static string Pozitie {
            get {
                return ResourceManager.GetString("Pozitie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puncte Forte.
        /// </summary>
        internal static string Puncteforte {
            get {
                return ResourceManager.GetString("Puncteforte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramase Anterior.
        /// </summary>
        internal static string RamaseAnterior {
            get {
                return ResourceManager.GetString("RamaseAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramase Curent.
        /// </summary>
        internal static string RamaseCurent {
            get {
                return ResourceManager.GetString("RamaseCurent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramase De Planificat.
        /// </summary>
        internal static string RamaseDePlanificat {
            get {
                return ResourceManager.GetString("RamaseDePlanificat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapoarte.
        /// </summary>
        internal static string rapoarte {
            get {
                return ResourceManager.GetString("rapoarte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapoart date pontaj angajati.
        /// </summary>
        internal static string RaportDatePontajAngajati {
            get {
                return ResourceManager.GetString("RaportDatePontajAngajati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raspuns.
        /// </summary>
        internal static string Raspuns {
            get {
                return ResourceManager.GetString("Raspuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realizat.
        /// </summary>
        internal static string Realizat {
            get {
                return ResourceManager.GetString("Realizat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respingere.
        /// </summary>
        internal static string Respingere {
            get {
                return ResourceManager.GetString("Respingere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schimba Parola.
        /// </summary>
        internal static string SchimbaParola {
            get {
                return ResourceManager.GetString("SchimbaParola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schimba parola.
        /// </summary>
        internal static string SchimbaParola2 {
            get {
                return ResourceManager.GetString("SchimbaParola2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situatie Zile CO Planificate pe luni.
        /// </summary>
        internal static string SituatieZileCOPlanificatePeLuni {
            get {
                return ResourceManager.GetString("SituatieZileCOPlanificatePeLuni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold Anterior.
        /// </summary>
        internal static string SoldAnterior {
            get {
                return ResourceManager.GetString("SoldAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitate.
        /// </summary>
        internal static string Solicitate {
            get {
                return ResourceManager.GetString("Solicitate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sterge.
        /// </summary>
        internal static string Sterge {
            get {
                return ResourceManager.GetString("Sterge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Realizare.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teme.
        /// </summary>
        internal static string Teme {
            get {
                return ResourceManager.GetString("Teme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termen.
        /// </summary>
        internal static string Termen {
            get {
                return ResourceManager.GetString("Termen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cuvenite.
        /// </summary>
        internal static string TotalCuvenite {
            get {
                return ResourceManager.GetString("TotalCuvenite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizator.
        /// </summary>
        internal static string Utilizator {
            get {
                return ResourceManager.GetString("Utilizator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versiune.
        /// </summary>
        internal static string Versiune {
            get {
                return ResourceManager.GetString("Versiune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zile CO Efectuate.
        /// </summary>
        internal static string ZileCOEfectuate {
            get {
                return ResourceManager.GetString("ZileCOEfectuate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zile CO Ramase.
        /// </summary>
        internal static string ZileCORamase {
            get {
                return ResourceManager.GetString("ZileCORamase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone De Dezvoltare.
        /// </summary>
        internal static string Zonededezvoltare {
            get {
                return ResourceManager.GetString("Zonededezvoltare", resourceCulture);
            }
        }
    }
}
