//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Meniu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Meniu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Meniu", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absente.
        /// </summary>
        internal static string Absente {
            get {
                return ResourceManager.GetString("Absente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrare.
        /// </summary>
        internal static string Administrare {
            get {
                return ResourceManager.GetString("Administrare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angajati.
        /// </summary>
        internal static string Angajati {
            get {
                return ResourceManager.GetString("Angajati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignare meniuri pe grupuri.
        /// </summary>
        internal static string AsiganreMeniuriPeGrupuri {
            get {
                return ResourceManager.GetString("AsiganreMeniuriPeGrupuri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignare angajati pe grupuri.
        /// </summary>
        internal static string AsignareAngajatiPeGrupuri {
            get {
                return ResourceManager.GetString("AsignareAngajatiPeGrupuri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignare intro pe grupuri.
        /// </summary>
        internal static string Asignareintropegrupuri {
            get {
                return ResourceManager.GetString("Asignareintropegrupuri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignare stire pe grupuri.
        /// </summary>
        internal static string AsignareStirePeGrupuri {
            get {
                return ResourceManager.GetString("AsignareStirePeGrupuri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cereri.
        /// </summary>
        internal static string Cereri {
            get {
                return ResourceManager.GetString("Cereri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creare Intro.
        /// </summary>
        internal static string CreareIntro {
            get {
                return ResourceManager.GetString("CreareIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creare meniuri.
        /// </summary>
        internal static string CreareMeniuri {
            get {
                return ResourceManager.GetString("CreareMeniuri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creare stiri.
        /// </summary>
        internal static string CreareStiri {
            get {
                return ResourceManager.GetString("CreareStiri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Angajati.
        /// </summary>
        internal static string DateAngajati {
            get {
                return ResourceManager.GetString("DateAngajati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupuri de angajati.
        /// </summary>
        internal static string GrupuriDeAngajati {
            get {
                return ResourceManager.GetString("GrupuriDeAngajati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupuri de utilizatori.
        /// </summary>
        internal static string GrupuriDeUtilizatori {
            get {
                return ResourceManager.GetString("GrupuriDeUtilizatori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meniuri - Admin.
        /// </summary>
        internal static string MeniuriAdmin {
            get {
                return ResourceManager.GetString("MeniuriAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomenclatoare.
        /// </summary>
        internal static string Nomenclatoare {
            get {
                return ResourceManager.GetString("Nomenclatoare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomenclator meniuri.
        /// </summary>
        internal static string NomenclatorMeniuri {
            get {
                return ResourceManager.GetString("NomenclatorMeniuri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prima Pagina.
        /// </summary>
        internal static string PrimaPagina {
            get {
                return ResourceManager.GetString("PrimaPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stiri.
        /// </summary>
        internal static string Stiri {
            get {
                return ResourceManager.GetString("Stiri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip Artera.
        /// </summary>
        internal static string TipArtera {
            get {
                return ResourceManager.GetString("TipArtera", resourceCulture);
            }
        }
    }
}
