//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WizOne.Generatoare.Reports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Report()
        {
            this.ReportUsers = new HashSet<ReportUser>();
            this.ReportGroupUsers = new HashSet<ReportGroupUser>();
        }
    
        public int ReportId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public short ReportTypeId { get; set; }
        public byte[] LayoutData { get; set; }
        public string RegUserId { get; set; }
        public string UpdUserId { get; set; }
        public System.DateTime RegDate { get; private set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
    
        public virtual ReportType ReportType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportUser> ReportUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportGroupUser> ReportGroupUsers { get; set; }
    }
}
