select CONVERT(int,ROW_NUMBER() OVER (ORDER BY (SELECT 1))) AS "IdAuto", TABLE_NAME, COLUMN_NAME, COLUMN_DEFAULT, IS_NULLABLE, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, 
NUMERIC_PRECISION, NUMERIC_SCALE from INFORMATION_SCHEMA.COLUMNS  where TABLE_NAME not in 
('ADDRESS', 'BENEFICII', 'CAEN_ITM', 'CCCLIENT', 'CLIENTI', 'CODURIPOSTALE', 'COMPACC', 'CONTRACTE', 'COR_ITM', 'CORECTIE', 'CRTEVAL',   'CURS_PENSIE_F',
 'DAILYCHANGES', 'DEPCLNT', 'ETICHETE', 'F1002', 'JUDETE', 'LOCALITATI', 'LOCATIE_MUNCA', 'LOCATII', 'MARDEF', 'MARTABLE',   'NOTACONT', 'NOTAPLAUTO', 
 'NROP_SOMAJ', 'ORASE_ITM', 'PENSIE_F', 'PERSCONT', 'PLAN_TABLE', 'PLCLIENT', 'POZE', 'PROCESE', 'PSTCLNT',   'RAPORT_DATE_ANGAJAT_TBL', 'REGISTRU_VECHIME', 
 'REPORTS', 'RSCPST', 'SALARIATI', 'SCHCLNT', 'SCRACC', 'SPORCLNT', 'SPORURI', 'SPVCLNT',    'STATUS', 'TABLEDEN', 'TAXE', 'TAXE_ARHIVA', 'USERHIST', 'ZileHand',
  'F100', 'F099', 'F1001', 'F0991')   and TABLE_NAME not like  'D00%' and TABLE_NAME not like 'D100%' and TABLE_NAME not like 'D110%' 
  and TABLE_NAME not like 'D205%' and TABLE_NAME not like 'F2%'   and TABLE_NAME not like 'F3%' and TABLE_NAME not like 'F4%' 
  and TABLE_NAME not like 'F5%' and TABLE_NAME not like 'F7%' and TABLE_NAME not like 'F9%'   and TABLE_NAME not like 'H0%' 
  and TABLE_NAME not like 'H1%' and TABLE_NAME not like 'REP_%' and TABLE_NAME not like 'WT_%'  and TABLE_NAME not like '%TMP%' 
  and TABLE_NAME not in (select TABLE_NAME from INFORMATION_SCHEMA.VIEWS)
  order by TABLE_NAME, COLUMN_NAME 